apiVersion: v1
kind: ServiceAccount
metadata:
  name: dummy-service
  namespace: application
  annotations:
        iam.gke.io/gcp-service-account: dummy-service@ggj-gke-test.iam.gserviceaccount.com

